In [2]:
import torch

#### - GPU 가용여부

In [10]:
if torch.cuda.is_available():
    print(f'{torch.cuda.current_device()}')
    print(f'{torch.cuda.get_device_name()}')
    print(f'{torch.cuda.get_device_capability()}')
else:
    print('No GPU!')

No GPU!


### - Tensor 생성 방법  (1)

In [14]:
# Tensor 속성 출력 함수 ---------------------------------------------
def printAttribute(tensor_, name):
    print(f'\n--- [{name}] ---')
    print(f'형태 : {tensor_.shape}, {tensor_.size()}')
    print(f'차원 : {tensor_.ndim}, {tensor_.dim()}')
    print(f'타입 : {tensor_.dtype}')
    print(f'위치 : {tensor_.device}')
    print(tensor_.data)

In [17]:
t1=torch.tensor([1,2,3,4])
t2=torch.tensor([11,22], dtype=torch.float16)
t3=torch.tensor([[1,1],[4,5]])
t4=torch.tensor(5)

In [18]:
printAttribute(t1, 't1')
printAttribute(t2, 't2')
printAttribute(t3, 't3')
printAttribute(t4, 't4')


--- [t1] ---
형태 : torch.Size([4]), torch.Size([4])
차원 : 1, 1
타입 : torch.int64
위치 : cpu
tensor([1, 2, 3, 4])

--- [t2] ---
형태 : torch.Size([2]), torch.Size([2])
차원 : 1, 1
타입 : torch.float16
위치 : cpu
tensor([11., 22.], dtype=torch.float16)

--- [t3] ---
형태 : torch.Size([2, 2]), torch.Size([2, 2])
차원 : 2, 2
타입 : torch.int64
위치 : cpu
tensor([[1, 1],
        [4, 5]])

--- [t4] ---
형태 : torch.Size([]), torch.Size([])
차원 : 0, 0
타입 : torch.int64
위치 : cpu
tensor(5)


- 특정 타입의 텐서 생성

In [58]:
t1=torch.FloatTensor([1,2])
t2=torch.IntTensor([11,22])
t3=torch.DoubleTensor([1,2])
t4=torch.CharTensor([1,2])
t5=torch.LongTensor([1,2])
t6=torch.BoolTensor([1,2,0])
t7=torch.Tensor([1,2,0])
t8=torch.Tensor([1.,2,0])

In [59]:
printAttribute(t1, 't1 - FloatTensor')
printAttribute(t2, 't2 - IntTensor')
printAttribute(t3, 't3 - DoubleTensor')
printAttribute(t4, 't4 - CharTensor')
printAttribute(t5, 't5 - LongTensor')
printAttribute(t6, 't6 - BoolTensor')
printAttribute(t7, 't7 - Tensor')
printAttribute(t8, 't8 - Tensor')


--- [t1 - FloatTensor] ---
형태 : torch.Size([2])
차원 : 1
타입 : torch.float32
위치 : cpu
tensor([1., 2.])

--- [t2 - IntTensor] ---
형태 : torch.Size([2])
차원 : 1
타입 : torch.int32
위치 : cpu
tensor([11, 22], dtype=torch.int32)

--- [t3 - DoubleTensor] ---
형태 : torch.Size([2])
차원 : 1
타입 : torch.float64
위치 : cpu
tensor([1., 2.], dtype=torch.float64)

--- [t4 - CharTensor] ---
형태 : torch.Size([2])
차원 : 1
타입 : torch.int8
위치 : cpu
tensor([1, 2], dtype=torch.int8)

--- [t5 - LongTensor] ---
형태 : torch.Size([2])
차원 : 1
타입 : torch.int64
위치 : cpu
tensor([1, 2])

--- [t6 - BoolTensor] ---
형태 : torch.Size([3])
차원 : 1
타입 : torch.bool
위치 : cpu
tensor([ True,  True, False])

--- [t7 - Tensor] ---
형태 : torch.Size([3])
차원 : 1
타입 : torch.float32
위치 : cpu
tensor([1., 2., 0.])

--- [t8 - Tensor] ---
형태 : torch.Size([3])
차원 : 1
타입 : torch.float32
위치 : cpu
tensor([1., 2., 0.])


### ▶ 특정값으로 채운 Tensor 생성

In [60]:
t1=torch.ones((2,))
t2=torch.ones((3,4))

In [61]:
printAttribute(t1, 't1')
printAttribute(t2, 't2')


--- [t1] ---
형태 : torch.Size([2])
차원 : 1
타입 : torch.float32
위치 : cpu
tensor([1., 1.])

--- [t2] ---
형태 : torch.Size([3, 4])
차원 : 2
타입 : torch.float32
위치 : cpu
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [62]:
t1=torch.zeros((2,))
t2=torch.zeros((3,4))

printAttribute(t1, 't1')
printAttribute(t2, 't2')


--- [t1] ---
형태 : torch.Size([2])
차원 : 1
타입 : torch.float32
위치 : cpu
tensor([0., 0.])

--- [t2] ---
형태 : torch.Size([3, 4])
차원 : 2
타입 : torch.float32
위치 : cpu
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [43]:
# 지정된 값으로 채운 Tensor
t1=torch.full((2,), 9)
t2=torch.full((3,),4)

printAttribute(t1, 't1')
printAttribute(t2, 't2')


--- [t1] ---
형태 : torch.Size([2]), torch.Size([2])
차원 : 1, 1
타입 : torch.int64
위치 : cpu
tensor([9, 9])

--- [t2] ---
형태 : torch.Size([3]), torch.Size([3])
차원 : 1, 1
타입 : torch.int64
위치 : cpu
tensor([4, 4, 4])


In [44]:
# 대각선으로만 1을 채운 Tensor, 대칭행렬
t1=torch.eye((3))
t2=torch.eye(2)
t3=torch.eye(2,4)

printAttribute(t1, 't1')
printAttribute(t2, 't2')
printAttribute(t3, 't3')


--- [t1] ---
형태 : torch.Size([3, 3]), torch.Size([3, 3])
차원 : 2, 2
타입 : torch.float32
위치 : cpu
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

--- [t2] ---
형태 : torch.Size([2, 2]), torch.Size([2, 2])
차원 : 2, 2
타입 : torch.float32
위치 : cpu
tensor([[1., 0.],
        [0., 1.]])

--- [t3] ---
형태 : torch.Size([2, 4]), torch.Size([2, 4])
차원 : 2, 2
타입 : torch.float32
위치 : cpu
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.]])


In [40]:
# 임의의 값으로 채운 Tensor
t1=torch.rand((2,3))
t2=torch.randn(3)
t3=torch.randint(low=0, high=3, size=(2,3))
printAttribute(t3, 't3')
printAttribute(t1, 't1')
printAttribute(t2, 't2')



--- [t3] ---
형태 : torch.Size([2, 3]), torch.Size([2, 3])
차원 : 2, 2
타입 : torch.int64
위치 : cpu
tensor([[1, 0, 1],
        [1, 1, 0]])

--- [t1] ---
형태 : torch.Size([2, 3]), torch.Size([2, 3])
차원 : 2, 2
타입 : torch.float32
위치 : cpu
tensor([[0.6968, 0.5226, 0.3855],
        [0.5747, 0.4869, 0.8993]])

--- [t2] ---
형태 : torch.Size([3]), torch.Size([3])
차원 : 1, 1
타입 : torch.float32
위치 : cpu
tensor([0.0055, 1.1748, 0.2235])


In [57]:
t1=torch.tensor([11.,22.])

In [58]:
t2=torch.as_tensor(t1)
t3=torch.tensor(t1)

C:\Users\kwon\AppData\Local\Temp\ipykernel_11312\4091555117.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t3=torch.tensor(t1)


In [59]:
t1[0]=5.9

In [61]:
t1, t2, t3

(tensor([ 5.9000, 22.0000]), tensor([ 5.9000, 22.0000]), tensor([11., 22.]))

In [62]:
import numpy as np

In [75]:
arr=np.linspace(1, 10, 6)

In [76]:
t1=torch.tensor(arr)

In [77]:
t2=torch.from_numpy(arr)
t3=torch.as_tensor(arr)

In [81]:
arr[0]=55

In [82]:
t1, t2, t3

(tensor([100.0000,   2.8000,   4.6000,   6.4000,   8.2000,  10.0000],
        dtype=torch.float64),
 tensor([55.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
        dtype=torch.float64),
 tensor([55.0000,  2.8000,  4.6000,  6.4000,  8.2000, 10.0000],
        dtype=torch.float64))

In [84]:
t3=torch.arange(2)
t4=torch.arange(1, 10)
t5=torch.arange(1, 10, 3)

In [85]:
printAttribute(t3, 't3')
printAttribute(t4, 't4')
printAttribute(t5, 't5')


--- [t3] ---
형태 : torch.Size([2]), torch.Size([2])
차원 : 1, 1
타입 : torch.int64
위치 : cpu
tensor([0, 1])

--- [t4] ---
형태 : torch.Size([9]), torch.Size([9])
차원 : 1, 1
타입 : torch.int64
위치 : cpu
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

--- [t5] ---
형태 : torch.Size([3]), torch.Size([3])
차원 : 1, 1
타입 : torch.int64
위치 : cpu
tensor([1, 4, 7])


In [86]:
t4=torch.linspace(1, 10, 2)

In [87]:
t4

tensor([ 1., 10.])

In [88]:
t4[0] , t4[-1]

(tensor(1.), tensor(10.))

In [89]:
t4[:3]

tensor([ 1., 10.])

In [90]:
t4[[1,-1]]

tensor([10., 10.])

In [95]:
t1=torch.FloatTensor([1,2])
t2=torch.FloatTensor([3,4])
t3=torch.FloatTensor([3])

In [96]:
t1, t2, t3

(tensor([1., 2.]), tensor([3., 4.]), tensor([3.]))

In [97]:
t4=t1+t2
t5=t1+t3

In [98]:
t4, t5

(tensor([4., 6.]), tensor([4., 5.]))

In [99]:
t1=torch.FloatTensor([[2,3]])
t2=torch.FloatTensor([[3],[4]])

In [102]:
t1, t1.shape

(tensor([[2., 3.]]), torch.Size([1, 2]))

In [103]:
t2, t2.shape

(tensor([[3.],
         [4.]]),
 torch.Size([2, 1]))

In [104]:
t3=t1+t2

In [105]:
t3

tensor([[5., 6.],
        [6., 7.]])

In [106]:
t4=t1*t2

In [107]:
t4

tensor([[ 6.,  9.],
        [ 8., 12.]])

In [108]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

In [109]:
print('Shape of Matrix 1: ', m1.shape)  
print('Shape of Matrix 2: ', m2.shape)

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])


In [110]:
m1*m2

tensor([[1., 2.],
        [6., 8.]])

In [111]:
m1.mul(m2)

tensor([[1., 2.],
        [6., 8.]])

In [113]:
m12=m1.matmul(m2)

In [114]:
m12.shape

torch.Size([2, 1])

In [115]:
m1

tensor([[1., 2.],
        [3., 4.]])

In [116]:
m2

tensor([[1.],
        [2.]])

In [125]:
x = torch.ones(2,3)   

In [126]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [127]:
x1=x.unsqueeze(dim=0)

In [128]:
x1.shape, 

(torch.Size([1, 2, 3]),)

In [129]:
x1

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [130]:
x2=x.unsqueeze(dim=-1)

In [132]:
x2, x2.shape

(tensor([[[1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.]]]),
 torch.Size([2, 3, 1]))

In [133]:
t1=torch.LongTensor([1,2,3,4])

In [138]:
t1.dtype

torch.int64

In [139]:
t2=t1.float()

In [140]:
t2.dtype

torch.float32

In [143]:
t3=t1.double()

In [145]:
t3.dtype

torch.float64

In [146]:
t4=t1.char()

In [148]:
t4.dtype

torch.int8

In [149]:
t5=t1.bool()

In [150]:
t5.dtype

torch.bool

In [151]:
t5

tensor([True, True, True, True])

In [168]:
w = torch.tensor(3.0, requires_grad = True)
y = w**3 + 10

In [169]:
y.backward()   # y 수식에 대한 미분 진행

In [171]:
print(f'y를 w로 미분한 값 : {w.grad}')
print(type(w))

y를 w로 미분한 값 : 27.0
<class 'torch.Tensor'>


In [155]:
import torch
import torch.nn as nn

In [156]:
x = torch.ones(5)  # 입력
y = torch.zeros(3)  # 출력

w = torch.randn(5, 3, requires_grad=True) # 가중치
b = torch.randn(3, requires_grad=True) # 편향

In [157]:
z = torch.matmul(x, w) + b
loss_fn = nn.MSELoss() # 손실 함수

In [158]:
loss = loss_fn(z, y)

loss.backward()

In [159]:
print(f'loss를 w로 미분한 값 :\n {w.grad}')
print(f'loss를 b로 미분한 값 : {b.grad}')

loss를 w로 미분한 값 :
 tensor([[-0.2401,  0.6350,  1.4047],
        [-0.2401,  0.6350,  1.4047],
        [-0.2401,  0.6350,  1.4047],
        [-0.2401,  0.6350,  1.4047],
        [-0.2401,  0.6350,  1.4047]])
loss를 b로 미분한 값 : tensor([-0.2401,  0.6350,  1.4047])


### PyTorch 파일 수정입니다.